[AIRFLOW-5050] Correctly delete FAB permission m2m objects in sync_perms (#5679)
Without this fix we can end up in the situation where trying to delete
throws an error:

    > psycopg2.IntegrityError: update or delete on table
    > "ab_permission_view" violates foreign key constraint
    > "ab_permission_view_role_permission_view_id_fkey" on table
    > "ab_permission_view_role"
    > DETAIL:  Key (id)=(57) is still referenced from table
    "ab_permission_view_role".

(cherry picked from commit a9666a4a6826fe7ed50730780951437f757d1d7b)